# Generated by Django 3.2.4 on 2021-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.FileField(default='MEDIA_ROOT/images/noprofile.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='MEDIA_ROOT/images/nolocation.png', upload_to='images'),
        ),
    ]
