# Generated by Django 3.2.4 on 2021-06-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210630_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.FileField(default='./uploads/images/noprofile.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='./uploads/images/nolocation.png', upload_to='images'),
        ),
    ]
