# Generated by Django 3.2.4 on 2021-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.FileField(default='uploads/images/noprofile.png', upload_to='images'),
        ),
    ]
