# Generated by Django 3.2.4 on 2021-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(default='https://www.pngarea.com/pngm/0/4941568_location-icon-png-location-logo-png-hd-hd.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', max_length=1000),
        ),
    ]
