# Generated by Django 3.2.4 on 2021-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210630_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
